//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Properties {
    using System;


    /// <summary>
    ///   Класс ресурсов со строгой типизацией для поиска локализованных строк и т. д.
    /// </summary>
    // Этот класс был автоматически сгенерирован StronglyTypedResourceBuilder
    // класс с помощью такого инструмента, как ResGen или Visual Studio.
    // Чтобы добавить или удалить участника, отредактируйте файл .ResX, а затем повторно запустите ResGen
    // с параметром /str или перестройте проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Переопределяет свойство CurrentUICulture текущего потока для всех
        /// поиск ресурсов с использованием этого строго типизированного класса ресурсов.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///  Ищет локализованный ресурс типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emoticon {
            get {
                object obj = ResourceManager.GetObject("emoticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Ищет локализованный ресурс типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconClose {
            get {
                object obj = ResourceManager.GetObject("IconClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
